/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ClauText */

#include "ClauText.h"
#include "clautextlib.h"

static wiz::ClauTextLib clau;


JNIEXPORT void JNICALL Java_ClauText_Clear
(JNIEnv *, jobject)
{
	clau.Clear();
}

	/*
	* Class:     ClauText
	* Method:    LoadDataFromFile
	* Signature: (Ljava/lang/String;)V
	*/
JNIEXPORT void JNICALL Java_ClauText_LoadDataFromFile
(JNIEnv * env, jobject, jstring jstr)
{
	const char* str = env->GetStringUTFChars(jstr, NULL);

	clau.LoadDataFromFile(str);

	env->ReleaseStringUTFChars(jstr, str);
}

	/*
	* Class:     ClauText
	* Method:    LoadDataFromString
	* Signature: (Ljava/lang/String;)V
	*/
JNIEXPORT void JNICALL Java_ClauText_LoadDataFromString
(JNIEnv * env, jobject, jstring jstr)
{
	const char* str = env->GetStringUTFChars(jstr, NULL);

	clau.LoadDataFromString(str);

	env->ReleaseStringUTFChars(jstr, str);
}

	/*
	* Class:     ClauText
	* Method:    SaveData
	* Signature: (Ljava/lang/String;)V
	*/
JNIEXPORT void JNICALL Java_ClauText_SaveData
(JNIEnv * env, jobject, jstring jstr)
{
	const char* str = env->GetStringUTFChars(jstr, NULL);

	clau.SaveData(str);

	env->ReleaseStringUTFChars(jstr, str);
}

	/*
	* Class:     ClauText
	* Method:    RunEventString
	* Signature: (Ljava/lang/String;)Ljava/lang/String;
	*/
JNIEXPORT jstring JNICALL Java_ClauText_RunEventString
(JNIEnv * env, jobject, jstring jstr)
{
	const char* str = env->GetStringUTFChars(jstr, NULL);

	std::string result = clau.RunEventString(str);

	env->ReleaseStringUTFChars(jstr, str);
	
	return env->NewStringUTF(result.c_str());
}


	/*
	* Class:     ClauText
	* Method:    RunEventFile
	* Signature: (Ljava/lang/String;)Ljava/lang/String;
	*/
JNIEXPORT jstring JNICALL Java_ClauText_RunEventFile
(JNIEnv * env, jobject, jstring jstr)
{
	const char* str = env->GetStringUTFChars(jstr, NULL);

	std::string result = clau.RunEventFile(str);

	env->ReleaseStringUTFChars(jstr, str);

	return env->NewStringUTF(result.c_str());
}
